name: BuringPlanet
version: 1.0-SNAPSHOT
main: xyz.trinets.minecraft.buringplanet.BuringPlanet
api-version: 1.13
authors: [TriNet, PMH]
description: Overworld is Buring
website: https://github.com/tritiumNetworks/BuringPlanet
